#!/bin/bash

exec > >(tee /tmp/check-challenge-2.log) 2>&1
set -uxo pipefail

su - irisowner <<'EOSU'
cat <<'EOF' | iris session iris -UUSER
kill errors
set sql = "SELECT ID FROM HoleFoods.Product WHERE SKU='SKU-976'"
set msg = "Have you inserted the new product into the database?"
do ##class(%zInstruqt.CheckExtras).CheckSQLReturnsResults(sql, msg,.errors)
do ##class(%zInstruqt.Check).Failure(.errors)
EOF
EOSU

EXIT=$?

exit $EXIT