#!/bin/bash

exec > >(tee /tmp/solve-challenge-2.log) 2>&1
set -euxo pipefail


su - irisowner <<'EOSU'
cat <<'EOF' | iris session iris -UUSER
set tRes=##class(%SQL.Statement).%ExecDirect(,"SELECT ID FROM HoleFoods.Product WHERE SKU='SKU-976'")
set hasRow = tRes.%Next()
set sql = "INSERT INTO HoleFoods.Product (Category, Name, Price, SKU, Stock) VALUES ('Snack', 'Gummy Rings', 2.99, 'SKU-976', 200)"
w:hasRow "Skipping addition, product already exists"
set stmt = ##class(%SQL.Statement).%New()
set sc = stmt.%Prepare(sql)
set:'hasRow rset = stmt.%Execute()
w:($g(rset)=""&'hasRow) "SQL error"
w:'hasRow "Adding Product"


halt
EOF
EOSU

exit 0
