services:
  iris:
    image: intersystems/iris-community:latest-em
    build: .
    ports:
      - "52773:52773"
      - "8025:8025"
    volumes:
      - ./:/home/irisowner/intro-to-iris-instruqt
  #   depends_on:
  #     - mailpit
  # mailpit:
  #   image: axllent/mailpit:latest
  #   ports:
  #     - "8025:8025"
  #     - "1025:1025"
