#!/bin/bash

exec > >(tee /tmp/check-challenge-3.log) 2>&1
set -uxo pipefail


su - irisowner <<'EOSU'
cat <<'EOF' | iris session iris -UUSER

set sql = "SELECT ID FROM HoleFoods.Product WHERE SKU='SKU-976' AND Stock=300"
set msg = "Have you restocked the Gummy Rings?"
do ##class(%zInstruqt.CheckExtras).CheckSQLReturnsResults(sql, msg, .errors)
do ##class(%zInstruqt.Check).Failure(.errors)
halt
EOF
EOSU

EXIT=$?

exit $EXIT