#!/bin/bash


exec > /tmp/startup-challenge3.log 2>&1
set -x
set -euxo pipefail

chown -R coder:coder /opt/intersystems

su - coder <<EOSU


cd /opt/intersystems/
mkdir -p src/challenge-3
cd src/challenge-3
mkdir HoleFoods
mkdir .vscode

cat <<EOF>> .vscode/settings.json 
{
    "workbench.colorTheme": "Default Dark+",
    "intersystems.servers": {
        "iris-52773": {
            "webServer": {
                "scheme": "http",
                "host": "iris",
                "port": 52773
            },
            "username": "SuperUser",
            "password": "SYS"
        }
    },
    "terminal.integrated.enableMultiLinePasteWarning": "never",
    "chat.disableAIFeatures": true
}
EOF

cat <<EOF>> .vscode/keybindings.json
[
    {
        "key": "ctrl+alt+t",
        "command": "vscode-objectscript.launchWebSocketTerminal"
    }
]
EOF

cat <<EOF>>/opt/intersystems/src/challenge-3/HoleFoods/ProductChanges.cls
Class HoleFoods.ProductChanges Extends %RegisteredObject
{

/// Prints the details of a product in the database
ClassMethod PrintProductDetails(pId As %String) As %Status
{
        // Open product by ID 
        set product = ##class(HoleFoods.Product).%OpenId(pId)

        // Write properties to terminal
        write !,!
        write "Product SKU: "_product.SKU, !
        write "Product Name: "_product.Name, !
        write "Product Category: "_product.Category,!
        write "Product Price: "_product.Price ,! 
        write "Product in Stock: "_product.Stock
        write !
}

/// Restock the product with new stock
ClassMethod Restock(id As %String, newStock As %Numeric) As %Status [ Language = python ]
{
        import iris #Embedded Python IRIS module

        # Open Product by ID
        product = iris.HoleFoods.Product._OpenId(id)

        old_stock = product.Stock

        # Add the new stock to the existing value
        product.Stock = product.Stock + newStock

        print(f"Restocking product, there is now {product.Stock} of {product.Name} units in stock")

        # Save the changes to the database
        out = product._Save()
}

}
EOF
EOSU
