#!/bin/bash

exec > >(tee /tmp/solve-challenge-3.log) 2>&1
set -euxo pipefail

su - irisowner <<'EOSU'
cat <<'EOF' | iris session iris -UUSER
do ##class(HoleFoods.ProductChanges).Restock("SKU-976", 100)
EOF
EOSU