#!/bin/bash

exec > >(tee /tmp/check-challenge-4.log) 2>&1
set -uxo pipefail



su - irisowner <<'EOSU'
cat <<'EOF' | iris session iris -UUSER

set sql = "SELECT ID FROM HoleFoods.SalesTransaction WHERE Product->SKU='SKU-976'"
set msg = "Have you submit an Order using the web form?" 

do ##class(%zInstruqt.CheckExtras).CheckSQLReturnsResults(sql,msg,.errors)

do ##class(%zInstruqt.CheckExtras).CheckComponentFunctioning("EmailOperation", .errors)

set sql = "SELECT ID FROM Ens_Util.Log WHERE ConfigName = 'EmailOperation' and SourceMethod='SendMail'"
set msg = "Have you re-submitted an order with the EmailOperation functioning?"
do ##class(%zInstruqt.CheckExtras).CheckSQLReturnsResults(sql,msg,.errors)

do ##class(%zInstruqt.Check).Failure(.errors)
EOCOS

EXIT=$?

exit $EXIT