#!/bin/bash

set -euxo pipefail


exec > >(tee /tmp/setup-challenge-1.log) 2>&1

apt-get update && apt-get install -y curl


## If is activated in Instruqt
## else is activated Locally 
## This ensures the same container setup is created for both. it works fine for both 
if [ ! -d "/home/irisowner/intro-to-iris-instruqt" ]; then
	apt-get update && apt-get install -y git
	cd /home/irisowner
	ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
	git clone https://www.github.com/isc-ging/intro-to-iris-instruqt

else 
  /home/irisowner/intro-to-iris-instruqt/sandbox-setup.sh
fi


su - irisowner <<'EOSU'


cat <<'EOF' | iris session iris -UUSER
do $system.OBJ.Import("/home/irisowner/intro-to-iris-instruqt/src/HoleFoods", "cuk")
do ##class(HoleFoods.Utils).StopJournalling("USER")
do ##class(HoleFoods.Utils).Setup()
halt
EOF



cat > /tmp/CheckExtras.cls << EOF 

Class %zInstruqt.CheckExtras
{

ClassMethod CheckSQLReturnsResults(sql As %String, failureMsg As %String, ByRef errors)
{
  Set tRes = ##class(%SQL.Statement).%ExecDirect(,sql)
  Set hasRow = tRes.%Next()
  
  If 'hasRow {
    write failureMsg,!
    do ##class(%zInstruqt.Check).AddError(.errors, failureMsg)
  }
}

ClassMethod CheckComponentFunctioning(component As %String, ByRef errors){
  
  Set enabled = ##class(Ens.Director).IsItemEnabled(component, .status)
  set failureMsg = ""
  if $$$ISERR(status){
    set failureMsg = "Have you add the "_component_" to the production?"
  } elseif 'enabled{ 
    set failureMsg = "Have you ensured the "_component_" component is running?"
  }
  
  if failureMsg '= ""{
    write failureMsg,!
    do ##class(%zInstruqt.Check).AddError(.errors, failureMsg)
  }

}
}



EOF


cat <<'EOF' | iris session iris -UUSER

do ##class(%SYSTEM.OBJ).Load("/tmp/CheckExtras.cls", "cuk")
s version="latest" s r=##class(%Net.HttpRequest).%New(),r.Server="pm.community.intersystems.com",r.SSLConfiguration="ISC.FeatureTracker.SSL.Config" d r.Get("/packages/zpm/"_version_"/installer"),$system.OBJ.LoadStream(r.HttpResponse.Data,"c")
zpm
repo -r -n registry -url https://pm.community.intersystems.com/ -user "" -pass ""
exit
halt
EOF


EOSU


