#!/bin/bash

set -euxo pipefail


exec > >(tee /tmp/setup-challenge-1.log) 2>&1

apt-get update && apt-get install -y curl
MAILPIT_VERSION="v1.27.7"

ARCH="$(uname -m)"

case "$ARCH" in
    x86_64) FILE="mailpit-linux-amd64.tar.gz" ;;
    aarch64|arm64) FILE="mailpit-linux-arm64.tar.gz" ;;
    *)
        echo "Unsupported architecture: $ARCH"
        exit 1
        ;;
esac

curl -fsSL \
    "https://github.com/axllent/mailpit/releases/download/${MAILPIT_VERSION}/${FILE}" \
    -o /tmp/mailpit.tar.gz

tar -xzf /tmp/mailpit.tar.gz -C /usr/local/bin
chmod +x /usr/local/bin/mailpit


nohup mailpit \
  --listen 0.0.0.0:8025 \
  --smtp 0.0.0.0:1025 \
  > /var/log/mailpit.log 2>&1 &

sleep 2

pgrep -a mailpit || {
  echo "Mailpit failed to stay running"
  cat /var/log/mailpit.log
  exit 1
}


if [ ! -d "/home/irisowner/intro-to-iris-instruqt" ]; then
	apt-get update && apt-get install -y git
	cd /home/irisowner
	ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
	git clone https://www.github.com/isc-ging/intro-to-iris-instruqt
fi


su - irisowner <<'EOSU'

cat <<'EOF' | iris session iris -U%SYS
do ##class(Security.Users).UnExpireUserPasswords("*")
do ##class(Security.Users).Create("tech","%ALL","demo")
do ##class(Security.Users).AddRoles("UnknownUser","%ALL")
set rs= ##class(Security.Applications).ListFunc("/csp/*")
set p("AutheEnabled")=64, p("UseCookies") = 1
while rs.%Next() { do ##class(Security.Applications).Modify(rs.Name,.p) }
do ##class(%SYSTEM.OBJ).Load("/tmp/Instruqt.Check.cls","ck")
do ##class(%SYSTEM.OBJ).Load("/tmp/zstart.mac","ck")
do ##class(%zInstruqt.Check).HideSQLPane()

halt
EOF


cat <<'EOF' | iris session iris -UUSER
do $system.OBJ.Import("/home/irisowner/intro-to-iris-instruqt/src/HoleFoods", "cuk")
do ##class(HoleFoods.Utils).StopJournalling("USER")
do ##class(HoleFoods.Utils).Setup()
halt
EOF

EOSU
