#!/bin/bash

exec > >(tee /tmp/check-challenge-4.log) 2>&1
set -uxo pipefail



su - irisowner <<'EOSU'
cat <<'EOF' | iris session iris -UUSER
kill errors
set sql = "SELECT ID FROM HoleFoods.SalesTransaction WHERE Product->SKU='SKU-976'"
set msg = "Have you submit an Order using the web form?" 

do ##class(%zInstruqt.CheckExtras).CheckSQLReturnsResults(sql,msg,.errors)
do ##class(%zInstruqt.Check).Failure(.errors)

do ##class(%zInstruqt.CheckExtras).CheckComponentFunctioning("ToEmail", .errors)
do ##class(%zInstruqt.Check).Failure(.errors)

set sql = "SELECT ID FROM Ens_Util.Log WHERE ConfigName = 'ToEmail' and SourceMethod='SendMail'"
set msg = "Have you re-submitted an order with the ToEmail functioning?"
do ##class(%zInstruqt.CheckExtras).CheckSQLReturnsResults(sql,msg,.errors)

do ##class(%zInstruqt.Check).Failure(.errors)
halt
EOCOS

EXIT=$?

exit $EXIT