#!/bin/bash

set -euxo pipefail

exec > >(tee /tmp/setup-challenge-4.log) 2>&1

su - irisowner <<'EOSU'

iris session IRIS -U USER <<'EOF'
write "Loading interop classes...",!
set tSC = $system.OBJ.Import("/home/irisowner/intro-to-iris-instruqt/src/HoleFoods", "cuk")
if $$$ISERR(tSC) { do $system.Status.DisplayError(tSC) halt }

write "Running setup...",!
set tSC = ##class(HoleFoods.Interop.Setup).Run()
if $$$ISERR(tSC) { do $system.Status.DisplayError(tSC) halt }

write "Challenge 4 setup complete.",!
halt
EOF

EOSU

# Copy web pages to CSP directory
cp /home/irisowner/intro-to-iris-instruqt/src/order.html          /usr/irissys/csp/user/order.html
cp /home/irisowner/intro-to-iris-instruqt/src/thankyou.html       /usr/irissys/csp/user/thankyou.html
cp /home/irisowner/intro-to-iris-instruqt/src/thankyou-noemail.html /usr/irissys/csp/user/thankyou-noemail.html
cp /home/irisowner/intro-to-iris-instruqt/src/quiz.html     /usr/irissys/csp/user/quiz.html